# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: terraform-backend-library

stages:
  - stage: plan
    jobs:
    - job: terraform_plan
      steps:
      - script: terraform --version
        displayName: 'check terraform version'
      - task: AzureCLI@2
        displayName: "Terraform Init"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            ./env_setup.sh
            echo $TF_VAR_container_name
            terraform init --backend-config=backend.tfvars
        env:
          TF_VAR_subscription_id: $(TF_VAR_subscription_id)
          TF_VAR_storage_account_name: $(TF_VAR_storage_account_name)
          TF_VAR_resource_group_name: $(TF_VAR_resource_group_name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(TF_VAR_container_name)
      - script: |
          terraform plan -out theplan
        displayName: 'terraform plan'

  - stage: apply
    jobs:
    - job: terraform_apply
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script apply'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script apply'


